### ISSUE TITLE
Looking for a proper way to handle connection errors.

### ISSUE THREAD

**Issue by barca-reddit** [PLhery/node-twitter-api-v2#92]
Hello folks, thanks for developing and maintaining this library. I have a question, or two questions actually if you don't mind.

Right now I am running a bot that is connected to a Twitter stream, which listens for tweets from an array of users, and then I do some fancy stuff with it. The problem is, every once in a while, Twitter throws a 429 error at me, maybe once every 24-48 hrs, and as a result of that I get an unhandledRejection error, and then the Stream no longer works without manually restarting the bot.

```
app[worker.1]: Error: Request failed with code 429
app[worker.1]: at RequestHandlerHelper.createResponseError (/app/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:73:16)
app[worker.1]: at IncomingMessage.<anonymous> (/app/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:114:33)
app[worker.1]: at IncomingMessage.emit (node:events:402:35)
app[worker.1]: at endReadableNT (node:internal/streams/readable:1343:12)
app[worker.1]: at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Here is a simplified version of my code:

```js
class _Twitter {
    constructor({ streamName }) {
        this.streamName = streamName;
    }

    async initSources() {
        const sourceList = [
            'Barca_Buzz', 'barcacentre', 'BarcaTimes', 'BarcaUniversal', 'FCBarcelona',
            'FCBarcelonaFl', 'GSpanishFN', 'infosfcb', 'LaSenyera', 'ReshadRahman_',
        ];

        const streamRules = await this.client.v2.streamRules();

        // Cleanup all existing rules upon initiating
        if (streamRules?.data?.length > 0) {
            await this.client.v2.updateStreamRules({
                delete: {
                    ids: streamRules.data.map(rule => rule.id),
                },
            });
        }

        await this.client.v2.updateStreamRules({
            add: sourceList.map(source => ({
                value: `(from:${source}) -is:retweet -is:reply`,
                tag: source.name
            }))
        });
    }

    async stream() {
        try {
            this.client = new TwitterApi(TwitterBearerToken);
            await this.initSources();

            this.stream = await this.client.v2.searchStream(
                {
                    "tweet.fields": ['id', 'text', 'created_at', 'entities'],
                    "user.fields": ['username', 'name', 'profile_image_url'],
                    'media.fields': ['preview_image_url', 'url', 'width', 'height', 'type'],
                    'expansions': ['author_id', 'attachments.media_keys']
                }
            );

            this.stream.autoReconnect = true;
            this.stream.autoReconnectRetries = 999;

            // Listen for all possible events (for debugging purposes);

            this.stream.on(ETwitterStreamEvent.Data, async (data) => {
                console.log(`Event: Data (${data.includes.users[0].username})\n---`);
                // do something with the tweet here
            });

            this.stream.on(ETwitterStreamEvent.ConnectionClosed, async (data) => {
                console.log(`Event: ConnectionClosed${data ? `\n${JSON.stringify(data, null, 4)}\n` : '\n'}---`);
            });
            this.stream.on(ETwitterStreamEvent.ConnectionError, async (data) => {
                console.log(`Event: ConnectionError${data ? `\n${JSON.stringify(data, null, 4)}\n` : '\n'}---`);
            });
            this.stream.on(ETwitterStreamEvent.ConnectionLost, async (data) => {
                console.log(`Event: ConnectionLost${data ? `\n${JSON.stringify(data, null, 4)}\n` : '\n'}---`);
            });
            this.stream.on(ETwitterStreamEvent.DataError, async (data) => {
                console.log(`Event: DataError${data ? `\n${JSON.stringify(data, null, 4)}\n` : '\n'}---`);
            });
            this.stream.on(ETwitterStreamEvent.DataKeepAlive, async (data) => {
                console.log(`Event: DataKeepAlive${data ? `\n${JSON.stringify(data, null, 4)}\n` : '\n'}---`);
            });
            this.stream.on(ETwitterStreamEvent.Error, async (data) => {
                console.log(`Event: Error${data ? `\n${JSON.stringify(data, null, 4)}\n` : '\n'}---`);
            });
            this.stream.on(ETwitterStreamEvent.ReconnectAttempt, async (data) => {
                console.log(`Event: ReconnectAttempt${data ? `\n${JSON.stringify(data, null, 4)}\n` : '\n'}---`);
            });
            this.stream.on(ETwitterStreamEvent.ReconnectLimitExceeded, async (data) => {
                console.log(`Event: ReconnectLimitExceeded${data ? `\n${JSON.stringify(data, null, 4)}\n` : '\n'}---`);
            });
            this.stream.on(ETwitterStreamEvent.Reconnected, async (data) => {
                console.log(`Event: Reconnected${data ? `\n${JSON.stringify(data, null, 4)}\n` : '\n'}---`);
            });
            this.stream.on(ETwitterStreamEvent.TweetParseError, async (data) => {
                console.log(`Event: TweetParseError${data ? `\n${JSON.stringify(data, null, 4)}\n` : '\n'}---`);
            });

        } catch (error) {
            console.log(this.streamName, 'error');
            console.log(error);

            if (error.code = 429) {
                await this.stream.reconnect();
            }
        }
    }
}

const Twitter1 = new _Twitter({ streamName: 'Stream 1' });

(async () => {
    await Twitter1.stream();
})();
```

So as you can see, I am creating a `_Twitter` class, and then creating an instance of that class to connect to the Streaming API. This all works fine, except that only the `Data` and `DataKeepAlive` events are emitting properly, and the rest goes into my `catch` block. 

~~It also appears that `autoReconnect` and `autoReconnectRetries` are not a properties of `this.stream`, and `reconnect()` is not a valid method either. I think the problem is that I have to use and implement the `TweetStream` into my code, but I am not sure how to exactly, and I can't find documentation for this either.~~

In any case, I don't want to make this too long, so I would just like to ask if you can point me in the right direction, such as providing a very quick example if that is possible.

Thank you for your time.

EDIT: It appears that `this.stream` is in fact a `TweetStream` object, there was just an error with my test script.

I would still like to ask, is this the proper way to implement `autoReconnect`? The actual code on my server does not have this `try catch` block, because I just assumed it would reconnect automatically on any kind of connection error. I'm not sure how to test this properly because Twitter only allows for 1 concurrent stream.

**Comment by barca-reddit** [comment]
> Auto-reconnect should work in your case, but it **does not handle the first initial connection, that is a classic request**. It's why the `TweetStream` is obtained through a `Promise`: it await for request acception by Twitter before resolving.

Allow me to clarify something. I became aware of the fact that my example above is failing, and in addition to that I am also now aware that `await this.client.v2.searchStream(...)` returns a promise (`TweetStream`), that needs to connect successfully at least once (upon start), and because Twitter only allows for one concurrent stream, my demo was failing immediately, thus I was getting `undefined` inside the `catch` block and as such `.reconnect()` was not working. All of that is clear to me now, apologies for the poor code.

With all of that in mind, before I wrote this reply here, I had production code with `autoReconnect` enabled on my server, and one which successfully connects to a Twitter stream. But as mentioned, it was failing to reconnect when an error occasionally occurs and it required a manual restart. Here is the full code without any edits:

```js
const { ETwitterStreamEvent, TweetStream, TwitterApi, ETwitterApiError } = require('twitter-api-v2');
const { MessageActionRow, MessageButton } = require('discord.js');
const TwitterSources = require('../models/twitter-sources');
const Discord = require('../util/discord');

class Twitter {
    stripAt(handle) {
        return handle.replace(/^@/, '');
    }

    stripShorteners(text) {
        return text.replace(/\shttps:\/\/t\.co\/[\S]{5,}$/gmi, '');
    }

    async getSourceRuleId(handle) {
        const sourceList = await this.client.v2.streamRules();
        console.log(sourceList);
        return sourceList.data.find(source => source.tag.toLowerCase() === handle.toLowerCase()).id;
    }

    async listSources() {
        const sourceList = await this.client.v2.streamRules();
        if (sourceList.data) {
            return sourceList.data
                .map(source => `\`@${source.tag}\``)
                .sort((a, b) => a.localeCompare(b))
                .join(', ');
        }
        else {
            return 'No entries found.';
        }
    }

    async addSource(handle) {
        handle = this.stripAt(handle);

        await TwitterSources.findOneAndUpdate(
            { name: new RegExp(handle, 'i') },
            { name: handle },
            { upsert: true, runValidators: true }
        );
        await this.client.v2.updateStreamRules({
            add: [
                {
                    value: `(from:${handle}) -is:retweet -is:reply`,
                    tag: handle
                }
            ]
        });

        return true;
    }

    async removeSource(handle) {
        handle = this.stripAt(handle);

        await TwitterSources.findOneAndDelete({ name: new RegExp(handle, 'i') });
        await this.client.v2.updateStreamRules({
            delete: { ids: [await this.getSourceRuleId(handle)] }
        });

        return true;
    }

    async initSources() {
        const sourceList = await TwitterSources.find({}).lean();
        const streamRules = await this.client.v2.streamRules();

        if (streamRules?.data?.length > 0) {
            await this.client.v2.updateStreamRules({
                delete: {
                    ids: streamRules.data.map(rule => rule.id),
                },
            });
        }

        await this.client.v2.updateStreamRules({
            add: sourceList.map(source => ({
                value: `(from:${source.name}) -is:retweet -is:reply`,
                tag: source.name
            }))
        });
    }

    embedTweet(data) {
        return ({
            description: data.text,
            url: data.url,
            color: 15329769,
            timestamp: data.time,
            footer: {
                text: data.authorName,
                icon_url: data.authorPhoto
            },
            ...data.thumbnail && {
                thumbnail: {
                    url: data.thumbnail
                }
            }
        })
    }

    embedActions(data) {
        return new MessageActionRow()
            .addComponents(
                new MessageButton({
                    label: 'Source',
                    style: 'LINK',
                    url: data.url,
                }),
                new MessageButton({
                    customId: 'POST_ON_REDDIT',
                    label: 'Post on Reddit',
                    style: 'SECONDARY',
                    emoji: '776887363901063189'
                })
            );
    }

    async stream() {
        this.client = new TwitterApi(process.env.TWITTER_BEARER_TOKEN);
        await this.initSources();

        this.stream = await this.client.v2.searchStream(
            {
                "tweet.fields": ['id', 'text', 'created_at', 'entities'],
                "user.fields": ['username', 'name', 'profile_image_url'],
                'media.fields': ['preview_image_url', 'url', 'width', 'height', 'type'],
                'expansions': ['author_id', 'attachments.media_keys']
            }
        );
        this.stream.autoReconnect = true;
        this.stream.autoReconnectRetries = 999;

        this.stream.on(ETwitterStreamEvent.Data, async (tweet) => {
            const author = tweet.includes.users.find(user => user.id === tweet.data.author_id);
            const tweetData = {
                id: tweet.data.id,
                url: `https://twitter.com/${author.username}/status/${tweet.data.id}`,
                authorName: author.username,
                authorPhoto: author.profile_image_url,
                text: this.stripShorteners(tweet.data.text),
                time: new Date(tweet.data.created_at).getTime(),
                ...tweet?.includes?.media?.[0]?.url && {
                    thumbnail: tweet.includes.media[0].url
                }
            }

            await Discord.channels.cache
                .get(process.env.TWITTER_CHANNEL_ID)
                .send({
                    embeds: [this.embedTweet(tweetData)],
                    components: [this.embedActions(tweetData)]
                });
        });
    }
}

const twitter = new Twitter();

module.exports = twitter;
```

Provided that there is no `try catch` block here, what is the purpose of `autoReconnect` if you have to intercept the error and use the `reconnect()` method anyway?

In any case, please don't consider responding to me a priority as I don't want to take too much of your time, I have working code now anyway so not a big deal.

**Comment by barca-reddit** [comment]
Hello again, apologies for reopening this issue but I've ran into some unexpected problems, and I was hoping you can help me figure it out.

Basically I have made the suggested adjustments to my code since we last talked, and pushed them to my production server for the Discord bot that I am running. This morning I found out that the bot has crashed because it ran out of memory.

It appears that I've lost connection to the Twitter stream, and `ETwitterStreamEvent.ReconnectAttempt` and `ETwitterStreamEvent.Error` were continuously emitting in an extremely short interval of time until it the crash:

```
2021-10-14T19:39:41.636845+00:00 app[worker.1]: Twitter Event:ReconnectAttempt: null
2021-10-14T19:39:41.727128+00:00 app[worker.1]: Twitter Event:Error: {"type":"reconnect error","error":{}}
2021-10-14T19:39:41.728673+00:00 app[worker.1]: Twitter Event:ReconnectAttempt: null
2021-10-14T19:39:41.819645+00:00 app[worker.1]: Twitter Event:Error: {"type":"reconnect error","error":{}}
2021-10-14T19:39:41.821180+00:00 app[worker.1]: Twitter Event:ReconnectAttempt: null
2021-10-14T19:39:41.896057+00:00 app[worker.1]: Twitter Event:Error: {"type":"reconnect error","error":{}}
2021-10-14T19:39:41.897486+00:00 app[worker.1]: Twitter Event:ReconnectAttempt: null
2021-10-14T19:39:42.148890+00:00 app[worker.1]: Twitter Event:Error: {"type":"reconnect error","error":{}}
```

As you can see, these events were emitted mere milliseconds between each other, and I had thousands of those entries in my log files. Since then I have turned off the bot and I was able to reproduce this same behavior on my local machine. Here is a full sample that you can also run:

```js
const { TwitterApi, ETwitterStreamEvent } = require('twitter-api-v2');

class Twitter {
    async startStream() {
        try {
            this.client = new TwitterApi(TWITTER_BEARER_TOKEN);
            this.stream = await this.client.v2.searchStream(
                {
                    "tweet.fields": ['id', 'text', 'created_at', 'entities'],
                    "user.fields": ['username', 'name', 'profile_image_url'],
                    'media.fields': ['preview_image_url', 'url', 'width', 'height', 'type'],
                    'expansions': ['author_id', 'attachments.media_keys']
                }
            );

            console.log('Connected to the Twitter stream');

            this.stream.autoReconnect = true;
            this.stream.autoReconnectRetries = Infinity;

            this.stream.on(ETwitterStreamEvent.Data, async (tweet) => {
                console.log(tweet);
            });
            this.stream.on(ETwitterStreamEvent.Error, async (error) => {
                console.log(`Twitter Event:Error: ${JSON.stringify(error)}`);
            });
            this.stream.on(ETwitterStreamEvent.ReconnectAttempt, async () => {
                console.log(`Twitter Event:ReconnectAttempt`);
            });
            this.stream.on(ETwitterStreamEvent.Reconnected, async () => {
                console.log(`Twitter Event:Reconnected`);
            });
            this.stream.on(ETwitterStreamEvent.DataKeepAlive, async () => {
                console.log(`Twitter Event:DataKeepAlive`);
            });
        } catch (error) {
            console.log(error);
            await this.logError({ msg: `Unhandled Twitter Error. Check server logs.` });
        }
    }
}

const twitter = new Twitter();

(async () => {
    await twitter.startStream();
})();
```

To reproduce the disconnect and the subsequent flood of emits, I forcefully shut down the connections to `104.244.42.x` which is the IP range of `twitter.com` and `api.twitter.com`, usually it's `104.244.42.140` but it may vary.

On Linux, after I initially and successfully connect to the stream I run this command to find out which port it's running on - `sudo ss -t | grep 104.244` and then I used a tool called `tcpkill` to shut down the connection - `sudo tcpkill -i XXX port YYY`, where `YYY` is the name of my network, usually `eth0` or `eno1` and YYY is the port that is connected to the twitter stream.

After a few seconds, it kills the connection and the events start emitting like crazy.

```
Connected to the Twitter stream
Twitter Event:DataKeepAlive
Twitter Event:DataKeepAlive
Twitter Event:DataKeepAlive
```
```
#after I run tcpkill command:

Twitter Event:Error: {"type":"connection error","error":{"errno":-104,"code":"ECONNRESET","syscall":"read"}}
Twitter Event:ReconnectAttempt
Twitter Event:Error: {"type":"reconnect error","error":{}}
Twitter Event:ReconnectAttempt
Twitter Event:Error: {"type":"reconnect error","error":{}}
Twitter Event:ReconnectAttempt
Twitter Event:Error: {"type":"reconnect error","error":{}}
Twitter Event:ReconnectAttempt
Twitter Event:Error: {"type":"reconnect error","error":{}}
Twitter Event:ReconnectAttempt
Twitter Event:Error: {"type":"reconnect error","error":{}}
Twitter Event:ReconnectAttempt
```

I am not exactly sure why that's happening, because a few days ago I ran some tests before pushing the code on my server, and the disconnects were handled exactly as documented, or in particular:

> `.autoReconnectRetries: number` / default `5` / If `autoReconnect` is `true`, maximum tries made until give up. Each try is spaced by `min((attempt ** 2) * 1000, 25000)` milliseconds.

Do you have any idea why this might be happening?

**Comment by alkihis** [comment]
Hi again,
Many thanks for the detailed explanation of what's happening.

I don't really know what's happening and why the reconnect timeout isn't awaited.
I will look into it as quick as possible following your specific test case and I'll come back here with more infos.

**Comment by alkihis** [comment]
Hello again!

`autoReconnect` previously doesn't work with the initial connection, because of some tweaks.
With the new 1.6.2 update (yes, a new update again, sorry!), `autoReconnect` behaviour is now applied even for the initial connection. It means that you don't need to manually reconnect after a failed connect attempt.

It also means that `.connect` is a `Promise` that will never fail anymore on `autoReconnect: true`, because a possible error is catched and given to the `makeAutoReconnectRetry` stream chain, that will fire a new `.ConnectError` event (only when the initial connection fails), and `.ReconnectError` (as before) afterwards.

```ts
class Twitter {
    async startStream() {
    // await only the first connection to be failed or succeeded
    // you must log .on(.ConnectError) to know if the connection fails
    await this.stream.connect({
        autoReconnect: true,
        autoReconnectRetries: Infinity,
    });
}
```

**Comment by barca-reddit** [comment]
Gonna keep it ultra short this time. Another `ECONNRESET` today on my production server. I made 3 reconnect attempts in 90 seconds, then I called `stream.destroy()` and waited another 5 minutes. Tried to reconnect, but got the same error as before. After two additional attempts I shut down the whole server for another 3-4 minutes, but again, `TooManyConnections`.

15 minutes since the initial `ECONNRESET` it managed to reconnect. It's worth pointing out that I did not do any modifications to delay the first reconnect attempt, so just running the old code as before. But it seems to me that once you get stuck in this hole, there is no coming out unless you wait 15 minutes.

**Comment by alkihis** [comment]
Okay, a lot of discussion happend here in a week.
Here's my detailed response for all the debated things in that issue during the last couple of days.

- About occurencies of stream errors

  I've set, last sunday (October 24), on my personal VPS a running Twitter API v2 stream using the last version of the package (***1.6.4***).
  All connect/reconnect and error events has been logged since that day.

  During the last 8 days:
  - 27 disconnections, 24 initiated by Twitter (operational disconnect), 3 manually initiated (with `tcpkill`)
  - For every disconnection initiated by Twitter, the **first** reconnect attempt (made immediately after connection loss) is successful, **every time**
  - For each disconnection initiated by me, the **first** reconnect attempt always fails (Twitter seems to have a latency to detect abruptly closed streams). Stream has been recovered successfully after the **second attempt** (5 seconds after first attempt)

  So, on my side, no abnormal behavior has been detected.

- About `.connect`/`.reconnect`/`.clone` methods

  Methods `.connect`/`.reconnect` behaves like they were meant to work.
  No, it's not strange that `.connect` call `.reconnect`, because this is basically the same thing:
  1) If `res`/`req` are stored in instance, destroy them, clean the possibly started timeouts
  2) Make a new request to Twitter, obtain `IncomingResponse` (`res`) and `ClientRequest` (`req`) objects, and **store them in instance**
  3) If the request **FAILS**, initiate reconnect timeout: call `nextRetryTimeout` to get the number of ms to await before retrying, then go back to step 1
  4) If the request **SUCCEEDS**, bind all the listeners to those two objects in order to catch **data payloads** and **errors**

  Method `.clone` make the two first steps, but instead of storing `req` and `res` to current instance, it creates a fresh one and bind all the current listeners of this instance to the new one.
  As Twitter do not support two concurrent steams for now, this method is **completely useless**.

- Why reconnection always fails

  In Twitter documentation, they recommand to increment the waiting time between two requests with a exponential-like function, up to 30 seconds in order to minimize time where stream will be left without connect.
  
  Note that 15-minute window usually don't apply for streams, rate limiting is made quite differently and documentation found for REST-like endpoints is not really valid for stream-like endpoints. 
  I don't find any documentation, in v1 and v2 API, directly related to streaming endpoints, that mentionned a 15-minute rate limit window.

  @barca-reddit mentionned that, even if they're any connection to Twitter after the disconnection (checked with a list of open sockets), Twitter sometimes replies that rate limit is hit.

  Even if I don't encounter this problem, I suppose the problem is more on **Twitter side** than on **client side**. Even more if a server reboot doesn't fix the problem sometimes!

  If this issue resolves by itself by waiting 15 minutes (and not 30 seconds), I suggest that we can use a `nextRetryTimeout` that return a ms number up to `900000` (15 minutes) instead of the current 2 minutes cap.
  It can be **interesting to know if this issue also affects streams for v1 API**.

- Why `.reconnect` is fired immediately after connection error

  As I said before, we want to minimize time where stream is "offline". Reconnection process can be trigged after a 2 minutes timeout (`.ConnectionLost` event), as it is fired when a `ECONNRESET` happens (propagated through `error` event of `ClientRequest`).

  If we come from a timeout, we don't want to wait any longer, we want a reconnection now. And, **even if a reconnection is started "too soon"**, next attempts will follow later (at least we tried to recover as fast as possible!).

  Adding an artificial delay of 1-2 minutes after the initial disconnection (in a 429 error case) will not resolve the issue at all, because the problem seems to be a rate-limit cleanup issue on Twitter side.

  Also, reminder that before a reconnection attempt, previous request is **always** destroyed.

  One last thing, `.nextRetryTimeout` is called **AFTER** a reconnect attempt, so it's NOT called before the first one: parameter `tryOccurence` is never `0`.

The changes discussed before (up to 15 minutes for `.nextRetryTimeout` default function, and `error` parameter in `.nextRetryTimeout` for custom implementations) will be pushed soon on npm.

Hope it will help you to resolve your issues.

**Comment by barca-reddit** [comment]
Hey @alkihis, I just wanted to let you know that I haven't had any more 15 minute reconnect loops since the 15th of December last year, so that's around 20 days ago. I really haven't done or changed anything since my last comment in November, because I ran out of time and patience to deal with this issue and just decided to live with it.

But in any case, this just confirms what I suspected, which is that it was a problem with Twitter (or less likely with Heroku) that they have eventually fixed, and not a problem with this library.

So that's all, and finally I also wanted to say thank you again for providing help and even going lengths trying to reproduce the problem on your end, it is appreciated.

I'm closing this issue now because it's resolved (and hopefully it stays that way). Cheers!

**Comment by Zedifuu** [comment]
Hey guys, 

I forgot to also check back in, I have also stopped having reconnect rate limits also. 

I have a funny feeling this was fixed quietly by them when they [released API v2 from Early Access](https://twittercommunity.com/t/ushering-in-a-new-era-for-the-twitter-developer-platform-with-the-twitter-api-v2/162087)

I feel I was at most part trying to diagnose an issue that wasn't caused by us 😅 
Sorry for fuelling that rabbit hole! 

Wish you guys all the best with what you create And again @alkihis excellent work again!

**Comment by barjabeen12** [comment]
Hey is there anyone who is still getting this issue, i am facing this issue with stream. Now stream just stop listening to events and doesn't give any error. i have to manually restart the stream after 2 to 3 days.

**Comment by barca-reddit** [comment]
> Hey is there anyone who is still getting this issue, i am facing this issue with stream. **Now stream just stop listening to events and doesn't give any error.** i have to manually restart the stream after 2 to 3 days.

This is not the same issue as the one that we were discussing here for the most part. At least in my case I was unable to recover the connection after getting an `ECONNRESET` error and it stays down for like 15 minutes until it manages to recover. But I don't think I've ever had an instance where the connection dropped **without** any errors.

What I could quickly suggest is to bind a listener for the following events: `ConnectionError`, `ConnectionClosed`, `ConnectionLost`, `ConnectError`, `ReconnectError`, `ReconnectLimitExceeded`, `DataError`, `TweetParseError` and `Error` which would hopefully give you more details on why the disconnect is occurring.

https://github.com/PLhery/node-twitter-api-v2/blob/master/doc/streaming.md#events

I would also suggest creating a separate issue, the maintainers and devs of this library are quite helpful so they would probably help if you provide them with additional details.

---

By the way, despite [this comment](https://github.com/PLhery/node-twitter-api-v2/issues/92#issuecomment-1004539069) shortly after I started getting ECONNRESETs again, but I just don't have time, desire or energy to go down this rabbit hole again, so whatever. A few disconnects per month (5-10) isn't that big of a deal. It's most likely an issue with Twitter or less likely with Heroku.
